// ========== PROPERTY DATA ==========
window.properties = [
  {
    id: 1, type: 'buy', propType: 'Apartment', bhk: 3, price: 8500000, priceDisplay: '₹85 Lakh',
    title: 'Luxurious 3 BHK Flat in Premium Society', location: 'Sector 62, Noida', city: 'Noida',
    area: 1450, areaDisplay: '1,450 sq.ft', image: 'images/property-1.jpg',
    status: 'ready', verified: true, featured: true, newLaunch: false, rera: 'UP/2024/12345',
    amenities: ['Swimming Pool','Gym','Clubhouse','24x7 Security','Power Backup','Lift'],
    possession: 'Ready to Move', floor: '8th of 18', facing: 'East', parking: 1,
    description: 'A beautifully designed 3BHK apartment with modern amenities in a premium gated society. The apartment features large windows, modular kitchen, and stunning city views.',
    price_per_sqft: 5862,
  },
  {
    id: 2, type: 'buy', propType: 'Villa', bhk: 4, price: 18500000, priceDisplay: '₹1.85 Cr',
    title: 'Spacious 4 BHK Independent Villa with Garden', location: 'Whitefield, Bangalore', city: 'Bangalore',
    area: 3200, areaDisplay: '3,200 sq.ft', image: 'images/city-mumbai.jpg',
    status: 'ready', verified: true, featured: true, newLaunch: false, rera: 'KAR/2023/98765',
    amenities: ['Private Garden','Gym','Swimming Pool','Club House','Solar Power','Home Automation'],
    possession: 'Ready to Move', floor: 'Ground + 1', facing: 'North', parking: 2,
    description: 'An exquisite independent villa with a private garden, private pool and premium smart home automation.',
    price_per_sqft: 5781,
  },
  {
    id: 3, type: 'rent', propType: 'Apartment', bhk: 2, price: 32000, priceDisplay: '₹32,000/mo',
    title: 'Modern 2 BHK Semi-Furnished Apartment', location: 'Koramangala, Bangalore', city: 'Bangalore',
    area: 1100, areaDisplay: '1,100 sq.ft', image: 'images/hero-bg.jpg',
    status: 'ready', verified: true, featured: false, newLaunch: false, rera: null,
    amenities: ['Lift','Security','Power Backup','Car Parking','Intercom'],
    possession: 'Ready to Move', floor: '4th of 10', facing: 'West', parking: 1,
    description: 'A well-maintained 2BHK apartment available for rent in the heart of Koramangala.',
    price_per_sqft: 29,
  },
  {
    id: 4, type: 'buy', propType: 'Plot', bhk: 0, price: 4500000, priceDisplay: '₹45 Lakh',
    title: 'Prime Residential Plot in DTCP Approved Layout', location: 'Sarjapur Road, Bangalore', city: 'Bangalore',
    area: 2400, areaDisplay: '2,400 sq.ft', image: 'images/property-1.jpg',
    status: 'ready', verified: true, featured: false, newLaunch: true, rera: 'KAR/2024/11234',
    amenities: ['DTCP Approved','Roads','Water Supply','Electricity','Compound Wall'],
    possession: 'Immediate', floor: 'Ground', facing: 'East', parking: 0,
    description: 'A prime plot in a DTCP approved layout with all basic amenities set up.',
    price_per_sqft: 1875,
  },
  {
    id: 5, type: 'buy', propType: 'Apartment', bhk: 3, price: 12500000, priceDisplay: '₹1.25 Cr',
    title: 'Premium 3 BHK Flat in Sea View Tower', location: 'Bandra West, Mumbai', city: 'Mumbai',
    area: 1800, areaDisplay: '1,800 sq.ft', image: 'images/city-mumbai.jpg',
    status: 'ready', verified: true, featured: true, newLaunch: false, rera: 'MH/2023/55432',
    amenities: ['Sea View', 'Swimming Pool','Gym','Concierge','Valet Parking','SPA'],
    possession: 'Ready to Move', floor: '22nd of 35', facing: 'Sea Facing', parking: 2,
    description: 'Stunning 3BHK sea-facing apartment in the most sought-after location of Bandra West with panoramic ocean views.',
    price_per_sqft: 6944,
  },
  {
    id: 6, type: 'rent', propType: 'Apartment', bhk: 1, price: 18000, priceDisplay: '₹18,000/mo',
    title: 'Cozy 1 BHK Furnished Studio Apartment', location: 'Powai, Mumbai', city: 'Mumbai',
    area: 650, areaDisplay: '650 sq.ft', image: 'images/hero-bg.jpg',
    status: 'ready', verified: false, featured: false, newLaunch: false, rera: null,
    amenities: ['Fully Furnished','WiFi','AC','Security','Lift'],
    possession: 'Ready to Move', floor: '2nd of 8', facing: 'South', parking: 0,
    description: 'A fully furnished 1BHK perfect for working professionals in the Powai IT hub.',
    price_per_sqft: 28,
  },
  {
    id: 7, type: 'buy', propType: 'Apartment', bhk: 4, price: 22000000, priceDisplay: '₹2.2 Cr',
    title: 'Ultra-Luxury 4 BHK Penthouse with Terrace', location: 'DLF Phase 5, Gurgaon', city: 'Gurgaon',
    area: 4200, areaDisplay: '4,200 sq.ft', image: 'images/property-1.jpg',
    status: 'ready', verified: true, featured: true, newLaunch: true, rera: 'HR/2024/88321',
    amenities: ['Private Terrace','Jacuzzi','Home Theatre','Smart Home','Private Pool','Butler Service'],
    possession: 'Ready to Move', floor: '42nd (Top Floor)', facing: 'North-East', parking: 3,
    description: 'A magnificent penthouse that redefines luxury living with private terrace garden, outdoor jacuzzi, and breathtaking skyline views.',
    price_per_sqft: 5238,
  },
  {
    id: 8, type: 'buy', propType: 'Apartment', bhk: 2, price: 5800000, priceDisplay: '₹58 Lakh',
    title: 'Affordable 2 BHK Flat Near Metro Station', location: 'Dwarka Mor, Delhi', city: 'Delhi NCR',
    area: 980, areaDisplay: '980 sq.ft', image: 'images/city-mumbai.jpg',
    status: 'under-construction', verified: true, featured: false, newLaunch: true, rera: 'DL/2024/44556',
    amenities: ['Children Play Area','Community Hall','Security','Power Backup','Lift','Parking'],
    possession: 'Dec 2025', floor: '5th of 15', facing: 'West', parking: 1,
    description: 'Affordable and well-connected 2BHK flat just 5 minutes walk from Dwarka Mor Metro Station.',
    price_per_sqft: 5918,
  },
  {
    id: 9, type: 'rent', propType: 'Villa', bhk: 3, price: 65000, priceDisplay: '₹65,000/mo',
    title: 'Elegant 3 BHK Furnished Villa for Rent', location: 'HSR Layout, Bangalore', city: 'Bangalore',
    area: 2200, areaDisplay: '2,200 sq.ft', image: 'images/property-1.jpg',
    status: 'ready', verified: true, featured: false, newLaunch: false, rera: null,
    amenities: ['Fully Furnished','Private Garden','Parking','Security','Power Backup','AC All Rooms'],
    possession: 'Ready to Move', floor: 'G+1', facing: 'East', parking: 2,
    description: 'Tastefully furnished independent villa with a private garden, ideal for families.',
    price_per_sqft: 30,
  },
  {
    id: 10, type: 'rent', propType: 'Lodge', bhk: 0, price: 1500, priceDisplay: '₹1,500/night',
    title: 'Comfortable AC Lodge Room Near Station', location: 'Patliputra, Patna', city: 'Patna',
    area: 250, areaDisplay: '250 sq.ft', image: 'images/hero-bg.jpg',
    status: 'ready', verified: true, featured: false, newLaunch: false, rera: null,
    amenities: ['AC','WiFi','Attached Bathroom','Room Service','Hot Water'],
    possession: 'Ready to Move', floor: '1st', facing: 'East', parking: 1,
    description: 'Clean and comfortable AC lodge room available on daily/monthly basis. Suitable for travellers and students.',
    price_per_sqft: 6,
  },
];

const cities = [
  { name: 'Mumbai', count: '82,000+', gradient: 'linear-gradient(135deg,#E84118,#ff6b4a)', emoji: '🌅', img: 'images/city-mumbai.jpg' },
  { name: 'Delhi NCR', count: '1,25,000+', gradient: 'linear-gradient(135deg,#1A1A2E,#16213E)', emoji: '🏛️', img: 'images/hero-bg.jpg' },
  { name: 'Bangalore', count: '95,000+', gradient: 'linear-gradient(135deg,#10B981,#065F46)', emoji: '🌳', img: 'images/property-1.jpg' },
  { name: 'Hyderabad', count: '68,000+', gradient: 'linear-gradient(135deg,#F5A623,#D97706)', emoji: '💎', img: 'images/city-mumbai.jpg' },
  { name: 'Pune', count: '54,000+', gradient: 'linear-gradient(135deg,#6366F1,#4338CA)', emoji: '🌆', img: 'images/hero-bg.jpg' },
  { name: 'Chennai', count: '47,000+', gradient: 'linear-gradient(135deg,#06B6D4,#0369A1)', emoji: '🌊', img: 'images/property-1.jpg' },
  { name: 'Kolkata', count: '38,000+', gradient: 'linear-gradient(135deg,#EC4899,#BE185D)', emoji: '🌸', img: 'images/city-mumbai.jpg' },
  { name: 'Noida', count: '42,000+', gradient: 'linear-gradient(135deg,#8B5CF6,#6D28D9)', emoji: '🏙️', img: 'images/hero-bg.jpg' },
];
